debugging windows' pipeline

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,95 +6,95 @@ env:
   MODULE_NAME: tarn
 
 jobs:
-  test-linux:
-    runs-on: ubuntu-20.04
-    env:
-      OS: ubuntu
-    strategy:
-      matrix:
-        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10', '3.11' ]
-
-    services:
-      redis:
-        image: redis
-        ports:
-          - 6379:6379
-        options: --entrypoint redis-server
-
-      openssh-server:
-        image: linuxserver/openssh-server
-        ports:
-          - 2222:2222
-        env:
-          PUID: 1001
-          PGID: 1001
-          PASSWORD_ACCESS: 'true'
-          USER_NAME: remote_user
-          USER_PASSWORD: password
-        volumes:
-          - /tmp:/tmp
-
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Check the version and build the package
-        run: |
-          VERSION=$(python -c "from pathlib import Path; import runpy; folder, = {d.parent for d in Path().resolve().glob('*/__init__.py') if d.parent.is_dir() and (d.parent / '__version__.py').exists()}; print(runpy.run_path(folder / '__version__.py')['__version__'])")
-          MATCH=$(pip index versions $MODULE_NAME | grep "Available versions:" | grep $VERSION) || echo
-          echo $MATCH
-          if [ "$GITHUB_BASE_REF" = "master" ] && [ "$MATCH" != "" ]; then exit 1; fi
-          python setup.py sdist
-
-      - name: Create ssh key
-        run: |
-          mkdir ~/.ssh && chmod 770 ~/.ssh
-          cp tests/assets/ssh_config ~/.ssh/config
-          # make sure we can connect now
-          sshpass -p password ssh -o "StrictHostKeyChecking no" remote echo Ok
-
-      - name: Install
-        run: |
-          pip install dist/*
-          pip install -r tests/requirements.txt
-
-          cd tests
-          export MODULE_PARENT=$(python -c "import $MODULE_NAME, os; print(os.path.dirname($MODULE_NAME.__path__[0]))")
-          export MODULE_PARENT=${MODULE_PARENT%"/"}
-          cd ..
-          echo $MODULE_PARENT
-          echo "MODULE_PARENT=$(echo $MODULE_PARENT)" >> $GITHUB_ENV
-
-      - name: Setup docker-compose services
-        run: |
-          mkdir -p /tmp/http/storage
-          docker-compose -f tests/assets/docker-compose.yml up -d
-
-      - name: Test with pytest
-        run: |
-          pytest tests --junitxml=reports/junit-${{ matrix.python-version }}-${OS}.xml --cov="$MODULE_PARENT/$MODULE_NAME" --cov-report=xml --cov-branch
-      - name: Generate coverage report
-        run: |
-          coverage xml -o reports/coverage-${{ matrix.python-version }}-${OS}.xml
-          sed -i -e "s|$MODULE_PARENT/||g" reports/coverage-${{ matrix.python-version }}-${OS}.xml
-          sed -i -e "s|$(echo $MODULE_PARENT/ | tr "/" .)||g" reports/coverage-${{ matrix.python-version }}-${OS}.xml
-
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: reports-${{ matrix.python-version }}-${OS}
-          path: reports/*.xml
-        if: ${{ always() }}
-
-      - name: Upload coverage results
-        uses: codecov/codecov-action@v2
-        with:
-          fail_ci_if_error: true
-          files: reports/coverage-*.xml
-          verbose: true
+  #  test-linux:
+  #    runs-on: ubuntu-20.04
+  #    env:
+  #      OS: ubuntu
+  #    strategy:
+  #      matrix:
+  #        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10', '3.11' ]
+  #
+  #    services:
+  #      redis:
+  #        image: redis
+  #        ports:
+  #          - 6379:6379
+  #        options: --entrypoint redis-server
+  #
+  #      openssh-server:
+  #        image: linuxserver/openssh-server
+  #        ports:
+  #          - 2222:2222
+  #        env:
+  #          PUID: 1001
+  #          PGID: 1001
+  #          PASSWORD_ACCESS: 'true'
+  #          USER_NAME: remote_user
+  #          USER_PASSWORD: password
+  #        volumes:
+  #          - /tmp:/tmp
+  #
+  #    steps:
+  #      - uses: actions/checkout@v2
+  #      - name: Set up Python ${{ matrix.python-version }}
+  #        uses: actions/setup-python@v2
+  #        with:
+  #          python-version: ${{ matrix.python-version }}
+  #
+  #      - name: Check the version and build the package
+  #        run: |
+  #          VERSION=$(python -c "from pathlib import Path; import runpy; folder, = {d.parent for d in Path().resolve().glob('*/__init__.py') if d.parent.is_dir() and (d.parent / '__version__.py').exists()}; print(runpy.run_path(folder / '__version__.py')['__version__'])")
+  #          MATCH=$(pip index versions $MODULE_NAME | grep "Available versions:" | grep $VERSION) || echo
+  #          echo $MATCH
+  #          if [ "$GITHUB_BASE_REF" = "master" ] && [ "$MATCH" != "" ]; then exit 1; fi
+  #          python setup.py sdist
+  #
+  #      - name: Create ssh key
+  #        run: |
+  #          mkdir ~/.ssh && chmod 770 ~/.ssh
+  #          cp tests/assets/ssh_config ~/.ssh/config
+  #          # make sure we can connect now
+  #          sshpass -p password ssh -o "StrictHostKeyChecking no" remote echo Ok
+  #
+  #      - name: Install
+  #        run: |
+  #          pip install dist/*
+  #          pip install -r tests/requirements.txt
+  #
+  #          cd tests
+  #          export MODULE_PARENT=$(python -c "import $MODULE_NAME, os; print(os.path.dirname($MODULE_NAME.__path__[0]))")
+  #          export MODULE_PARENT=${MODULE_PARENT%"/"}
+  #          cd ..
+  #          echo $MODULE_PARENT
+  #          echo "MODULE_PARENT=$(echo $MODULE_PARENT)" >> $GITHUB_ENV
+  #
+  #      - name: Setup docker-compose services
+  #        run: |
+  #          mkdir -p /tmp/http/storage
+  #          docker-compose -f tests/assets/docker-compose.yml up -d
+  #
+  #      - name: Test with pytest
+  #        run: |
+  #          pytest tests --junitxml=reports/junit-${{ matrix.python-version }}-${OS}.xml --cov="$MODULE_PARENT/$MODULE_NAME" --cov-report=xml --cov-branch
+  #      - name: Generate coverage report
+  #        run: |
+  #          coverage xml -o reports/coverage-${{ matrix.python-version }}-${OS}.xml
+  #          sed -i -e "s|$MODULE_PARENT/||g" reports/coverage-${{ matrix.python-version }}-${OS}.xml
+  #          sed -i -e "s|$(echo $MODULE_PARENT/ | tr "/" .)||g" reports/coverage-${{ matrix.python-version }}-${OS}.xml
+  #
+  #      - name: Upload artifacts
+  #        uses: actions/upload-artifact@v2
+  #        with:
+  #          name: reports-${{ matrix.python-version }}-${OS}
+  #          path: reports/*.xml
+  #        if: ${{ always() }}
+  #
+  #      - name: Upload coverage results
+  #        uses: codecov/codecov-action@v2
+  #        with:
+  #          fail_ci_if_error: true
+  #          files: reports/coverage-*.xml
+  #          verbose: true
 
   test-windows:
     runs-on: windows-latest
@@ -102,7 +102,8 @@ jobs:
       OS: windows
     strategy:
       matrix:
-        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10', '3.11' ]
+        #        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10', '3.11' ]
+        python-version: [ 3.9 ]
 
     steps:
       - uses: actions/checkout@v2
@@ -120,13 +121,6 @@ jobs:
           pip install dist/*
           pip install -r tests/requirements.txt
 
-          cd tests
-          export MODULE_PARENT=$(python -c "import $MODULE_NAME, os; print(os.path.dirname($MODULE_NAME.__path__[0]))")
-          export MODULE_PARENT=${MODULE_PARENT%"/"}
-          cd ..
-          echo $MODULE_PARENT
-          echo "MODULE_PARENT=$(echo $MODULE_PARENT)" >> $GITHUB_ENV
-
       - name: Setup docker-compose services
         run: |
           mkdir -p /tmp/http/storage
@@ -134,12 +128,10 @@ jobs:
 
       - name: Test with pytest
         run: |
-          pytest tests --junitxml=reports/junit-${{ matrix.python-version }}-${OS}.xml --cov="$MODULE_PARENT/$MODULE_NAME" --cov-report=xml --cov-branch
+          pytest tests --junitxml=reports/junit-${{ matrix.python-version }}-${OS}.xml --cov-branch
       - name: Generate coverage report
         run: |
           coverage xml -o reports/coverage-${{ matrix.python-version }}-${OS}.xml
-          sed -i -e "s|$MODULE_PARENT/||g" reports/coverage-${{ matrix.python-version }}-${OS}.xml
-          sed -i -e "s|$(echo $MODULE_PARENT/ | tr "/" .)||g" reports/coverage-${{ matrix.python-version }}-${OS}.xml
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v2
@@ -147,10 +139,3 @@ jobs:
           name: reports-${{ matrix.python-version }}-${OS}
           path: reports/*.xml
         if: ${{ always() }}
-
-      - name: Upload coverage results
-        uses: codecov/codecov-action@v2
-        with:
-          fail_ci_if_error: true
-          files: reports/coverage-*.xml
-          verbose: true
